Repository FC-Toy-Project-9/Toy_Project1, pull requests merged in 2023-09, with the labels that each got.

#1 feat: TripDTO 생성
  src/main/java/domain/trip/dto/TripDTO.java
Labels: ⚒️ feature

#3 feat: json에서 여행 기록 조회, 삭제 기능 구현
  build.gradle
  src/main/java/domain/trip/exception/TripFileNotFoundException.java
  src/main/java/domain/trip/service/TripService.java
  src/test/java/domain/trip/service/TripServiceTest.java
Labels: ⚒️ feature

#7 fix: CI 파일 수정
  .github/workflows/gradle.yml
Labels: 🧑🏻‍🔧 fix

#14 feat: 글로벌 기능 구현
  src/main/java/global/dto/TripCsvDTO.java
  src/main/java/global/exception/TripFileNotFoundException.java
  src/main/java/global/util/FileUtil.java
  src/test/java/global/dto/TripCsvDTOTest.java
Labels: ⚒️ feature

#16 feat: CSV에서 여행 기록 조회, 삭제 기능 구현
  src/main/java/domain/trip/dto/TripDTO.java
  src/main/java/domain/trip/service/TripService.java
  src/main/java/global/dto/TripCsvDTO.java
  src/test/java/domain/trip/service/TripServiceTest.java
Labels: ⚒️ feature, 🚧 refactoring

#21 feat: 메인 메서드 구현 및 리팩토링, 기능 수정
  src/main/java/domain/itinerary/dto/ItineraryDTO.java
  src/main/java/domain/itinerary/exception/ItineraryNotFoundException.java
  src/main/java/domain/itinerary/service/ItineraryService.java
  src/main/java/domain/trip/dto/TripDTO.java
  src/main/java/domain/trip/service/TripService.java
  src/main/java/global/view/View.java
  src/main/java/main/Main.java
  src/test/java/domain/itinerary/service/ItineraryServiceTest.java
  src/test/java/domain/trip/service/TripServiceTest.java
Labels: ⚒️ feature, 🚧 refactoring, 🧑🏻‍🔧 fix

#25 test: JsonUtil 테스트 코드 주석 수정 및 DisplayName 적용
  src/test/java/global/util/JsonUtilTest.java
Labels: 🚧 refactoring

#27 refactor: 여행 정보 등록 기능 관련 코드수정 및 주석 추가
  src/main/java/domain/trip/service/TripIDGenerator.java
  src/main/java/domain/trip/service/TripService.java
  src/main/java/global/dto/TripCsvDTO.java
  src/main/java/global/util/InputUtil.java
Labels: 🚧 refactoring, 🧑🏻‍🔧 fix

#23 refactor: 코드 수정 및 주석 추가
  src/main/java/domain/itinerary/dto/ItineraryDTO.java
  src/main/java/domain/itinerary/service/ItineraryService.java
  src/main/java/global/view/View.java
  src/test/java/domain/itinerary/service/ItineraryServiceTest.java
Labels: 🚧 refactoring

#22 refactor: 코드 수정 및 주석 추가
  src/main/java/domain/trip/dto/TripDTO.java
  src/main/java/domain/trip/exception/TripFileNotFoundException.java
  src/main/java/domain/trip/service/TripService.java
  src/main/java/global/dto/TripCsvDTO.java
  src/main/java/global/exception/TripFileNotFoundException.java
  src/main/java/global/util/FileUtil.java
  src/main/java/global/view/View.java
  src/test/java/domain/trip/service/TripServiceTest.java
Labels: 🚧 refactoring

#28 docs: file sample 추가
  src/main/resources/trip/csv/trip_1.csv
  src/main/resources/trip/csv/trip_2.csv
  src/main/resources/trip/id.txt
  src/main/resources/trip/json/trip_1.json
  src/main/resources/trip/json/trip_2.json
Labels: 📚 document

#30 refactor: 테스트 코드 수정 및 주석 추가
  src/test/java/domain/trip/service/TripServiceTest.java
  src/test/java/global/dto/TripCsvDTOTest.java
Labels: 🚧 refactoring

#29 ci: 테스트 검사 추가
  .github/workflows/gradle.yml
Labels: 🧑🏻‍🔧 fix
